# Server configuration
server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=student
spring.datasource.password=student123

spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true